import './style.css';
import { blankPlan, coverage, makeId, nutrientLabels, samplePlan, status, totals, type Food, type NutrientKey, type Plan, type Target } from './model';
import { clearPlan, readPlan, writePlan } from './store';

const app = document.querySelector<HTMLDivElement>('#app')!;
const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
let demo = location.pathname === '/demo' || new URLSearchParams(location.search).get('demo') === '1';
let plan: Plan = blankPlan();
let notice = '';
let editingMeal: string | null = null;
let activeRoute = location.pathname;
const LICENSE_KEY = 'sb_license:nutrient-floor-planner';
let licensed = Boolean(localStorage.getItem(LICENSE_KEY));
const e = (s: string) => s.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c]!));
const n = (value: number) => Math.round(value * 10) / 10;
const namespace = () => demo ? 'demo:plan' : 'real:plan';

function titleFor(route: string) { return route === '/demo' ? 'Demo — Nutrient Floor' : route === '/privacy' ? 'Privacy — Nutrient Floor' : route === '/terms' ? 'Terms — Nutrient Floor' : 'Nutrient Floor — Plan meals around nutrient targets'; }
function link(path: string, label: string) { return `<a href="${path}" data-route ${activeRoute === path ? 'aria-current="page"' : ''}>${label}</a>`; }
function header() { return `<header class="site-header"><a class="wordmark" href="/" data-route aria-label="Nutrient Floor home"><span>NF</span>Nutrient Floor</a><nav aria-label="Main navigation">${link('/demo','Demo')}${link('/plan','Planner')}${link('/privacy','Privacy')}</nav></header>`; }
function footer() { return `<footer><p>Nutrient Floor is a private meal planner.</p><p>${link('/privacy','Privacy')} · ${link('/terms','Terms')} · Built by Param Factory · v1.0</p></footer>`; }
async function verifyLicense(token: string) { localStorage.setItem(LICENSE_KEY, token); licensed = true; try { const response = await fetch(`https://api.sociobot.in/api/v1/products/nutrient-floor-planner/verify?license=${encodeURIComponent(token)}`); const verdict = await response.json() as { valid: boolean }; if (!verdict.valid) { localStorage.removeItem(LICENSE_KEY); licensed = false; notice = 'This license is no longer active. You can buy a new upgrade.'; } else { notice = 'Upgrade active on this device.'; } } catch { notice = 'Your upgrade will be checked when you are online.'; } }
async function collectLicense() { const query = new URLSearchParams(location.search); const token = query.get('license'); if (!token) return; localStorage.setItem(LICENSE_KEY, token); licensed = true; query.delete('license'); history.replaceState({}, '', `${location.pathname}${query.size ? `?${query}` : ''}`); await verifyLicense(token); }
function demoBanner() { return demo ? `<aside class="demo-banner" aria-label="Demo mode"><span><strong>Demo</strong> — sample data, nothing is saved.</span><span><button class="text-button" data-action="reset-demo">Reset demo</button><button class="text-button" data-action="start-real">Start for real</button></span></aside>` : ''; }
function routeCopy(kind: 'privacy' | 'terms') { const privacy = `<h1>Your meal plan stays on this device.</h1><p>Nutrient Floor stores foods, targets, and meals in your browser’s local database. We do not run analytics or send your nutrition data to us.</p><h2>What is stored</h2><p>Your plan is stored locally until you export it, import another plan, or clear browser data. The demo uses a separate local space and is discarded when you leave.</p><h2>Optional purchase</h2><p>If you choose to buy the one-time upgrade, the Sociobot checkout receives payment details. Nutrient Floor stores only the license token in your browser.</p><h2>Contact</h2><p>For product questions, email <a href="mailto:hello@sociobot.in">hello@sociobot.in</a>.</p>`;
  const terms = `<h1>Use Nutrient Floor for personal meal planning.</h1><p>Nutrient Floor helps you compare user-supplied food values with targets you choose. It is not medical advice or a nutrition diagnosis.</p><h2>Your data</h2><p>You are responsible for checking food labels and source values. Keep an export if your plan matters to you.</p><h2>One-time upgrade</h2><p>An optional upgrade is sold by Sociobot, the merchant of record. A refunded or revoked license no longer unlocks paid features.</p><h2>No warranty</h2><p>The app is provided as-is, to the extent allowed by law.</p>`;
  return kind === 'privacy' ? privacy : terms;
}

function landing() {
  return `<main id="main"><section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">A PRIVATE MEAL PLANNING SHEET</p><h1 id="hero-title">Plan meals that meet your nutrient targets.</h1><p class="lede">For home cooks who want enough fibre or protein without logging every calorie.</p><div class="hero-actions"><a class="button primary" href="/demo" data-route>Try it with sample data</a><span>Loads a seven-food plan.</span></div><ul class="facts"><li>Stored on this device</li><li>Works offline after setup</li><li>$12 one-time upgrade</li></ul></div><figure class="hero-art"><img src="/assets/hero.webp" width="1200" height="800" fetchpriority="high" decoding="async" alt="Ingredients arranged across a blue kitchen planning sheet." /><figcaption>Original generated illustration; food values are entered by you.</figcaption></figure></section><section class="live-preview ruled"><div><p class="eyebrow">THE QUESTION IT ANSWERS</p><h2>Will this small menu clear my floor?</h2><p>Pick a few targets, save familiar foods, and place meal portions on a week.</p></div><div class="mini-board"><span>FIBRE</span><b>33.5 g</b><i>above 30 g floor</i><span>PROTEIN</span><b>75.5 g</b><i>above 75 g floor</i></div></section><section class="how" aria-labelledby="how-title"><h2 id="how-title">Plan a week in three steps</h2><ol><li><b>01 / Set a target</b><span>Choose a floor or limit in grams.</span></li><li><b>02 / Save trusted foods</b><span>Copy values from a label or source.</span></li><li><b>03 / Place meals</b><span>See gaps before you cook.</span></li></ol></section><section class="plain-note"><h2>What this does not do</h2><p>It does not count calories, diagnose health conditions, or upload a food diary.</p></section><section class="upgrade"><div><p class="eyebrow">OPTIONAL ONE-TIME UPGRADE</p><h2>${licensed ? 'Your upgrade is active.' : 'Keep the basic planner free.'}</h2><p>${licensed ? 'You can save more pantry foods and print your weekly sheet.' : '$12 adds unlimited pantry foods and a printable weekly sheet.'}</p></div>${licensed ? '<a class="button secondary" href="/plan" data-route>Open your planner</a>' : '<a class="button secondary" href="https://api.sociobot.in/api/v1/products/nutrient-floor-planner/checkout">Buy the $12 upgrade</a>'}<form data-form="license" class="license-form"><label>Have a license?<input name="license" required aria-label="License token" /></label><button class="text-button" value="save">Restore purchase</button></form></section></main>`;
}

function targetRows() { const week = coverage(plan); if (!plan.targets.length) return `<div class="empty"><p>No targets yet.</p><button class="button small" data-action="show-target">Add your first target</button></div>`; return `<div class="target-list">${plan.targets.map(target => { const actual = week[target.key]; const state = status(target, actual); const wording = state.passes ? 'on plan' : target.kind === 'min' ? `${n(state.difference)} g short` : `${n(state.difference)} g over`; return `<article class="target ${state.passes ? 'pass' : 'gap'}"><div><b>${e(target.label)}</b><small>${target.kind === 'min' ? 'floor' : 'limit'} · ${target.value} g</small></div><div class="meter" aria-label="${e(target.label)} ${n(actual)} of ${target.value} grams"><span style="width:${Math.min((actual / target.value) * 100, 100)}%"></span></div><div class="target-total"><b>${n(actual)} g</b><small>${wording}</small></div><button class="icon-button" data-action="delete-target" data-id="${target.id}" aria-label="Delete ${e(target.label)}">×</button></article>`; }).join('')}</div>`; }
function foodList() { if (!plan.foods.length) return `<div class="empty"><p>Your saved foods will appear here.</p><button class="button small" data-action="show-food">Add a food</button></div>`; return `<div class="food-list">${plan.foods.map(food => `<article class="food"><div><b>${e(food.name)}</b><small>per ${e(food.serving)} · ${e(food.source)}</small></div><div>${(['fibre','protein','sugar','saturatedFat'] as NutrientKey[]).filter(k => food.nutrients[k]).map(k => `<span>${food.nutrients[k]}g ${nutrientLabels[k].toLowerCase()}</span>`).join('')}</div><button class="icon-button" data-action="delete-food" data-id="${food.id}" aria-label="Delete ${e(food.name)}">×</button></article>`).join('')}</div>`; }
function mealCard(meal: Plan['meals'][number]) { const total = totals(meal.portions, plan.foods); return `<article class="meal" draggable="true" data-meal="${meal.id}"><div class="meal-top"><span class="day-label">${DAYS[meal.day]}</span><button class="icon-button" data-action="delete-meal" data-id="${meal.id}" aria-label="Delete ${e(meal.name)}">×</button></div><button class="meal-name" data-action="edit-meal" data-id="${meal.id}">${e(meal.name)}</button><p>${meal.portions.length ? meal.portions.map(p => `${p.amount}× ${e(plan.foods.find(f => f.id === p.foodId)?.name || 'missing food')}`).join(' · ') : 'No portions yet'}</p><div class="meal-total">${plan.targets.slice(0, 2).map(t => `${n(total[t.key])}g ${t.key}`).join(' · ') || 'Add targets'}</div></article>`; }
function planner() { return `<main id="main" class="app-main"><section class="planner-heading"><div><p class="eyebrow">WEEKLY COVERAGE / ${demo ? 'SAMPLE' : 'YOUR PLAN'}</p><h1>Build a week that clears your targets.</h1><p>Each value is per serving. Check your labels before you rely on a plan.</p></div><div class="toolbar"><button class="button small" data-action="export-json">Export plan</button><label class="button small file-button">Import plan<input type="file" accept="application/json" data-action="import-json" /></label>${licensed ? '<button class="button small" data-action="print-plan">Print week</button>' : ''}</div></section><section class="coverage-board ruled" aria-labelledby="coverage-title"><div class="board-head"><h2 id="coverage-title">Week at a glance</h2><span>${plan.meals.length} meal${plan.meals.length === 1 ? '' : 's'} planned</span></div>${targetRows()}</section><section id="planner" class="week" aria-labelledby="week-title"><div class="board-head"><h2 id="week-title">Place meals on your week</h2><button class="button small" data-action="new-meal">Add a meal</button></div><div class="days">${DAYS.map((day, i) => `<section class="day" data-day="${i}"><h3>${day}</h3>${plan.meals.filter(m => m.day === i).map(mealCard).join('')}<button class="add-meal" data-action="new-meal" data-day="${i}">+ Add meal</button></section>`).join('')}</div></section><section class="two-col"><section class="pantry ruled" aria-labelledby="pantry-title"><div class="board-head"><div><p class="eyebrow">SAVED FOOD LIST</p><h2 id="pantry-title">Your trusted pantry</h2></div><button class="button small" data-action="show-food">Add food</button></div>${foodList()}</section><section class="targets-panel" aria-labelledby="targets-title"><div class="board-head"><div><p class="eyebrow">3–5 CUSTOM TARGETS</p><h2 id="targets-title">Your nutrient targets</h2></div><button class="button small" data-action="show-target">Add target</button></div>${plan.targets.length ? `<p class="muted">Use a floor for enough of something. Use a limit for less of something.</p>` : ''}</section></section>${modal()}</main>`; }
function modal() { if (!editingMeal) return ''; if (editingMeal === 'food') return `<dialog open class="modal"><form method="dialog" data-form="food"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">NEW SAVED FOOD</p><h2>Add a food and its serving.</h2><label>Food name<input name="name" required maxlength="60" /></label><label>Serving<label class="hint">Example: ½ cup dry</label><input name="serving" required maxlength="40" /></label><label>Source or label<input name="source" required maxlength="80" placeholder="Label, packet at home" /></label><div class="nutrient-inputs">${(['fibre','protein','sugar','saturatedFat'] as NutrientKey[]).map(k => `<label>${nutrientLabels[k]} (g)<input type="number" name="${k}" min="0" step="0.1" value="0" required /></label>`).join('')}</div><button class="button primary" value="save">Save food</button></form></dialog>`; if (editingMeal === 'target') return `<dialog open class="modal"><form method="dialog" data-form="target"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">NEW TARGET</p><h2>Add a nutrient floor or limit.</h2><label>Target name<input name="label" required maxlength="45" placeholder="Fibre floor" /></label><label>Nutrient<select name="key">${(['fibre','protein','sugar','saturatedFat'] as NutrientKey[]).map(k => `<option value="${k}">${nutrientLabels[k]}</option>`).join('')}</select></label><label>Type<select name="kind"><option value="min">Minimum floor</option><option value="max">Maximum limit</option></select></label><label>Grams per week<input name="value" type="number" min="0.1" step="0.1" required /></label><button class="button primary" value="save">Save target</button></form></dialog>`; const meal = plan.meals.find(m => m.id === editingMeal); if (!meal) return ''; return `<dialog open class="modal"><form method="dialog" data-form="meal"><button class="close" value="cancel" aria-label="Close">×</button><p class="eyebrow">MEAL PORTIONS</p><h2>Edit this meal.</h2><label>Meal name<input name="name" value="${e(meal.name)}" required maxlength="60" /></label><label>Day<select name="day">${DAYS.map((d, i) => `<option value="${i}" ${meal.day === i ? 'selected' : ''}>${d}</option>`).join('')}</select></label><fieldset><legend>Portions</legend>${plan.foods.length ? plan.foods.map(f => `<label class="portion"><span>${e(f.name)} <small>per ${e(f.serving)}</small></span><input type="number" name="food:${f.id}" min="0" step="0.25" value="${meal.portions.find(p => p.foodId === f.id)?.amount || 0}" /></label>`).join('') : '<p>Add a food first, then return to this meal.</p>'}</fieldset><button class="button primary" value="save">Save meal</button></form></dialog>`; }
function appPage() { return `${header()}${demoBanner()}${planner()}${footer()}<div class="toast" role="status" aria-live="polite">${notice}</div>`; }
function render() { activeRoute = location.pathname; document.title = titleFor(activeRoute); let page = ''; if (activeRoute === '/privacy' || activeRoute === '/terms') page = `${header()}<main id="main" class="legal"><article>${routeCopy(activeRoute.slice(1) as 'privacy' | 'terms')}</article></main>${footer()}`; else if (activeRoute === '/' && !demo) page = `${header()}${landing()}${footer()}`; else page = appPage(); app.innerHTML = page; if (notice) setTimeout(() => { notice = ''; const toast = document.querySelector('.toast'); if (toast) toast.textContent = ''; }, 3000); }
async function save() { await writePlan(namespace(), plan); }
async function load() { plan = await readPlan(namespace()); if (demo && !plan.meals.length) { plan = samplePlan(); await save(); } render(); }
function navigate(path: string) { history.pushState({}, '', path); if (path === '/demo') { demo = true; load(); } else { demo = false; load(); } window.scrollTo(0,0); }
function download(name: string, content: string, type = 'application/json') { const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([content], { type })); a.download = name; a.click(); URL.revokeObjectURL(a.href); }

document.addEventListener('click', async event => { const el = (event.target as HTMLElement).closest<HTMLElement>('[data-action], [data-route]'); if (!el) return; const route = el.closest<HTMLAnchorElement>('[data-route]'); if (route) { event.preventDefault(); navigate(route.pathname); return; } const action = el.dataset.action; const id = el.dataset.id!; if (action === 'show-food') { if (!licensed && plan.foods.length >= 10) { notice = 'The free planner holds 10 foods. Upgrade for more.'; render(); return; } editingMeal = 'food'; render(); } if (action === 'show-target') { editingMeal = 'target'; render(); } if (action === 'new-meal') { const meal = { id: makeId(), name: 'New meal', day: Number(el.dataset.day || 0), portions: [] }; plan.meals.push(meal); editingMeal = meal.id; await save(); render(); } if (action === 'edit-meal') { editingMeal = id; render(); } if (action === 'delete-target') { plan.targets = plan.targets.filter(t => t.id !== id); await save(); notice = 'Target removed.'; render(); } if (action === 'delete-food') { plan.foods = plan.foods.filter(f => f.id !== id); plan.meals.forEach(m => m.portions = m.portions.filter(p => p.foodId !== id)); await save(); notice = 'Food removed from pantry and meals.'; render(); } if (action === 'delete-meal') { plan.meals = plan.meals.filter(m => m.id !== id); await save(); notice = 'Meal removed.'; render(); } if (action === 'reset-demo') { await clearPlan('demo:plan'); plan = samplePlan(); await save(); notice = 'Sample plan reset.'; render(); } if (action === 'start-real') { demo = false; plan = await readPlan('real:plan'); if (!plan.targets.length && !plan.foods.length) plan = blankPlan(); await save(); notice = 'Your private plan is ready.'; history.replaceState({}, '', '/plan'); render(); } if (action === 'export-json') { download('nutrient-floor-plan.json', JSON.stringify(plan, null, 2)); notice = 'Plan exported as JSON.'; render(); } if (action === 'print-plan') window.print(); });
document.addEventListener('submit', async event => { const form = event.target as HTMLFormElement; if (!form.dataset.form) return; event.preventDefault(); const data = new FormData(form); if (form.dataset.form === 'license') { await verifyLicense(String(data.get('license'))); render(); return; } if ((event as SubmitEvent).submitter?.getAttribute('value') !== 'save') { editingMeal = null; render(); return; } if (form.dataset.form === 'food') { const nutrients = Object.fromEntries((['fibre','protein','sugar','saturatedFat'] as NutrientKey[]).map(k => [k, Number(data.get(k))])) as Food['nutrients']; plan.foods.push({ id: makeId(), name: String(data.get('name')), serving: String(data.get('serving')), source: String(data.get('source')), nutrients }); notice = 'Food saved to your pantry.'; } if (form.dataset.form === 'target') { plan.targets.push({ id: makeId(), label: String(data.get('label')), key: data.get('key') as NutrientKey, kind: data.get('kind') as Target['kind'], value: Number(data.get('value')), unit: 'g' }); notice = 'Target saved.'; } if (form.dataset.form === 'meal') { const meal = plan.meals.find(m => m.id === editingMeal)!; meal.name = String(data.get('name')); meal.day = Number(data.get('day')); meal.portions = plan.foods.map(f => ({ foodId: f.id, amount: Number(data.get(`food:${f.id}`)) })).filter(p => p.amount > 0); notice = 'Meal saved to your week.'; } editingMeal = null; await save(); render(); });
document.addEventListener('change', async event => { const input = event.target as HTMLInputElement; if (input.dataset.action !== 'import-json' || !input.files?.[0]) return; try { const incoming = JSON.parse(await input.files[0].text()) as Plan; if (!Array.isArray(incoming.foods) || !Array.isArray(incoming.targets) || !Array.isArray(incoming.meals)) throw new Error(); plan = incoming; await save(); notice = 'Plan imported.'; } catch { notice = 'That file is not a Nutrient Floor plan. Choose an exported JSON file.'; } render(); });
window.addEventListener('popstate', load);
if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => undefined);
collectLicense().then(load);
